version: '3.8'
services:
  mongo:
    image: mongo
    container_name: aitutor
    ports:
      - '27017-27019:27017-27019'
    env_file:
      - .env
    networks:
      - template-local-net
    volumes:
      - mongo:/data/db

volumes:
  mongo:
    name: db-volume

networks:
  template-local-net:
