name: aitutor-backend-cloudrun-app
on:
  push:
    branches:
      - master
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: aitutor-backend
  RUN_REGION: us-east1
  # project-name but it can be anything you want    
  # REPO_NAME: aitutor-backend-cloudrun-app
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON}}


jobs:
  build-and-deploy:
    name: dEPLOY to Cloud Run
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          #auth with gcloud
        # setup gcloud CLI
        - id: "auth"
          uses: "google-github-actions/auth@v0"
          with:
            credentials_json: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
    
        # Build and push image to Google Container Registry
        - name: Build
          run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA

        - name: Deploy
          run: gcloud run deploy $APP_ID --image gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA --platform managed --region $RUN_REGION --allow-unauthenticated